### ISSUE TITLE
Invalid character

### ISSUE THREAD

**Issue by karneaud** [Media24si/vue-pagination#13]
I'm using your package with elixir and everything works fine in all browser EXCEPT IE11 which just leaves me with 

> SCRIPT1014: Invalid character
> File: backend-app.js, Line: 270, Column: 1

Line 270 in the compiled js is

````
eval("module.exports = {\r\n    template: `<nav>\r\n        <ul class=\"pagination\" v-if=\"pagination.last_page > 0\" :class=\"sizeClass\">\r\n            <li v-if=\"showPrevious()\" :class=\"{ 'disabled' : pagination.current_page <= 1 }\">\r\n                <span v-if=\"pagination.current_page <= 1\">\r\n                    <span aria-hidden=\"true\">{{ config.previousText }}</span>\r\n                </span>\r\n                \r\n                <a href=\"#\" 

.... // snippet
```

So you have any idea what is causing it?

**Comment by pogachar** [comment]
I don't think IE supports template literals. If you're using laravel elixir, use `mix.webpack()`. You might need to configure webpack a bit. Check this [stackoverflow link](http://stackoverflow.com/questions/34404496/webpack-not-converting-es6-to-es5) how to transpile es6 to es5.

**Comment by karneaud** [comment]
@pogachar Yes I had to alter your package to correct the issue. You might want to think about refactoring it as there are people who need to develop for IE :-)
