### ISSUE TITLE
Unexpected character '`' [./~/vue-bootstrap-pagination/vue-bootstrap-pagination.js:2,0]

### ISSUE THREAD

**Issue by ldelcampof** [Media24si/vue-pagination#17]
I'm having problems again, now with Laravel 5.4 when try to do npm run production. I'm having this:

`[14:27:58] ldelcampo:crm git:(v1.5*) $ npm run production

> @ production /Users/ldelcampo/Sites/crm
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                         

 ERROR  Failed to compile with 1 errors                                                                                                                                                 2:28:31 PM

 error  

/js/app.js from UglifyJs
Unexpected character '`' [./~/vue-bootstrap-pagination/vue-bootstrap-pagination.js:2,0][/js/app.js:32970,14]

                                                                                                    Asset      Size  Chunks                    Chunk Names
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1   20.1 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760    109 kB          [emitted]         
  fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512   45.4 kB          [emitted]         
 fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158   23.4 kB          [emitted]         
fonts/vendor/bootstrap-sass/bootstrap/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb     18 kB          [emitted]         
                                                                                               /js/app.js   1.24 MB       0  [emitted]  [big]  /js/app
                                                                                             /css/app.css    119 kB       0  [emitted]         /js/app
                                                                                        mix-manifest.json  66 bytes          [emitted]         

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "run" "production"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ production script 'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
`

this is my package.json

`{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.15.3",
    "babel-preset-latest": "^6.24.1",
    "bootstrap-sass": "^3.3.7",
    "cross-env": "^3.2.3",
    "jquery": "^3.1.1",
    "laravel-mix": "0.*",
    "lodash": "^4.17.4",
    "vue": "^2.2.*"
  },
  "dependencies": {
    "vue-bootstrap-pagination": "^2.10.2"
  }
}
`

**Comment by BostjanOb** [comment]
Try to use dev branch

**Comment by viktor42b** [comment]
I have the same issue. So I tried to work on the dev branch but I have :
```
ERROR in static/js/vendor.0d9db1cdebcbd774ed3c.js from UglifyJs
Unexpected token: punc (() [./~/vue-bootstrap-pagination/dist/vue-bootstrap-pagination.esm.js:19,0][static/js/vendor.0d9db1cdebcbd774ed3c.js:29108,9]
```

**Comment by vesakk** [comment]
Same error here.

> ERROR  Failed to compile with 1 errors                                                                                                                               5:38:54 PM
error
/js/vue_bundle.js from UglifyJs Unexpected character '`' [./~/vue-bootstrap-pagination/vue-bootstrap-pagination.js:2,0][/js/vue_bundle.js:53313,14]

**Comment by marcusvbp** [comment]
I got this issue too:

> ERROR in build.js from UglifyJs
> Unexpected character '`' [./~/vue-bootstrap-pagination/vue-bootstrap-pagination.js:2,0][build.js:64199,14]

**Comment by code2prog** [comment]
i have same error

**Comment by Neoglyph** [comment]
EDIT: removed my comment, since the code was not complete and could lead to performance issues.

**Comment by code2prog** [comment]
Suggested solution helps with the previous problem, but unfortunately it causes a new one.
Production build takes over 2 minutes, same with watch. It was taking couple seconds before. Waiting 2 minutes to see changes  is unacceptable

**Comment by pogachar** [comment]
Require the dev version of the package and import the .vue file in src folder.

**Comment by code2prog** [comment]
thanks for help

**Comment by ldelcampof** [comment]
@pogachar @code2prog can you help me? dev version of which package? using Babili my app.js still big, only 23kb difference.
![image](https://user-images.githubusercontent.com/7885054/27805828-9789b3ae-5ffc-11e7-91d8-0ccc0da46e97.png)

**Comment by code2prog** [comment]
After all i download this file https://github.com/Media24si/vue-pagination/blob/dev/src/vue-bootstrap-pagination.vue from Dev version and include my self in project instead use npm

**Comment by Neoglyph** [comment]
@ldelcampof don't use babili, use the dev version of the project
put this in your package.json
`"vue-bootstrap-pagination": "git://github.com/Media24si/vue-pagination.git#dev",`

@code2prog @ldelcampof if you're using the dev branch try updating the package. The production builds should now run successfully without the need of importing the .vue file in the src folder, to your project. #18 

then you can import the pagination component, with the following command
`import pagination from 'vue-bootstrap-pagination'`

**Comment by Neoglyph** [comment]
The issue was fixed, so I am closing this thread.

**Comment by stephenlake** [comment]
I don't see how this is fixed? Using a development version is a fix? Sounds more like a hazard.
