### ISSUE TITLE
Make it compatible with vue 2.0 (Only one line)

### ISSUE THREAD

**Issue by kJamesy** [Media24si/vue-pagination#4]
Replace `this.$set('pagination.current_page', page);` with `this.$set(this.pagination, 'current_page', page);` on [line 65](https://github.com/Media24si/vue-pagination/blob/master/vue-bootstrap-pagination.js#L65)

**Comment by pogachar** [comment]
Hopefully it should work with 2.0 now.

**Comment by kJamesy** [comment]
npm can't find the new version though - I see it's still looking at the old version: [https://www.npmjs.com/package/vue-bootstrap-pagination](https://www.npmjs.com/package/vue-bootstrap-pagination)

**Comment by pogachar** [comment]
Sorry about that. Forgot to npm publish. It's set to v2 now.

**Comment by kJamesy** [comment]
Yep, works now. Ta
