### ISSUE TITLE
Feature Request: Always Display Previous/Next Buttons

### ISSUE THREAD

**Issue by kJamesy** [Media24si/vue-pagination#5]
Could we always have the Previous and Next buttons displayed? Perhaps disable them instead of hiding them when the case necessitates.

**Comment by pogachar** [comment]
I added some configuration options to the package. See readme.
Offset prop has been removed and replaced by options prop which accepts an object with a few configuration options.

To always display prev/next set `options.alwaysShowPrevNext` to true.

**Comment by kJamesy** [comment]
Thank you very much, good sir. All working great
