### ISSUE TITLE
Callback Runs twice on load

### ISSUE THREAD

**Issue by kJamesy** [Media24si/vue-pagination#7]
I have a weird issue.
When my app loads, two calls are made to the server in quick succession.
I have dug around and found that it behaves correctly (only one fetch) if I just leave the pagination parameters with straightforward integer values:
`pagination: {
                    total: 0,
                    per_page: 25,
                    current_page: 1,
                    last_page: 0,
                    from: 1,
                    to: 25
                },`

The above works.
The moment I change it to the below, then it fetches remote data twice:
`pagination: {
                    total: 0,
                    per_page: this.paginate,
                    current_page: 1,
                    last_page: 0,
                    from: 1,
                    to: this.paginate
                },`

//this.paginate is set to 25

In my mounted() function, I call the method responsible for fetching the remote data.
I notice in your example that you don't manually call this, the plugin takes care of it somewhat.
However, if I don't make that call, then nothing happens.
It seems it's either fetch twice or not at all for me.
Any ideas?

**Comment by kJamesy** [comment]
Ok I have found the issue.
The plugin watches the value of `pagination.per_page`.
If this changes, then it calls `callback()`.

On receiving data from the server, we overwrite the pagination object with the server provided values.
The plugin treats this as a change in `pagination.per_page` and so calls `callback()` once again.

Now, we can fix this by simply checking to see if the value of `pagination.per_page` really changed before we call `callback()`

``` js
    watch: {
        'pagination.per_page' (newVal, oldVal) {
            if ( newVal != oldVal )
                this.callback();
        }
    },
```

On [this line](https://github.com/Media24si/vue-pagination/blob/master/vue-bootstrap-pagination.js#L77)

**Comment by pogachar** [comment]
Updated. Have you checked if you ever changed per_page from number to string?

**Comment by kJamesy** [comment]
Actually, `.toString()` did the trick! If you revert the update and just do `.toString()` on the `per_page` value from the server, the plugin behaves well!

I have a feeling because you are now doing a strict check in the watcher, it's now going to fail with the .toString() since we initialise the per_page data with an integer. I haven't made an update yet.

**Comment by pogachar** [comment]
'+' before variable changes it to number so that shouldn't be an issue.
.toString() isn't a good option because it should be an integer

**Comment by kJamesy** [comment]
Alright, I've got rid of the `.toString()` and updated to 2.10.1 - works perfectly.
