### ISSUE TITLE
Add page parameter in the url

### ISSUE THREAD

**Issue by phoenixgao** [Media24si/vue-pagination#8]
When I use this lib, how do I add the page parameter in the end of the url when I click the page link, so I can use that url to go to that page directly?

I'm using vue-router

**Comment by pogachar** [comment]
Look at [vue-router dynamic route matching](https://router.vuejs.org/en/essentials/dynamic-matching.html).

In your callback function change the route (look at programmatic navigation).
In created hook set current_page accordingly (or look at in-component navigation guards)
